/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhq_ndklibrary_StringUtil */

#ifndef _Included_com_dhq_ndklibrary_StringUtil
#define _Included_com_dhq_ndklibrary_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhq_ndklibrary_StringUtil
 * Method:    spiltStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dhq_ndklibrary_StringUtil_spiltStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
