/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhq_ndkdemo_util_StringUtil */

#ifndef _Included_com_dhq_ndkdemo_util_StringUtil
#define _Included_com_dhq_ndkdemo_util_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhq_ndkdemo_util_StringUtil
 * Method:    append
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dhq_ndkdemo_util_StringUtil_append
  (JNIEnv *env, jclass class, jstring str){
    return (*env)->NewStringUTF(env,"这里是来自c的string1");
}

#ifdef __cplusplus
}
#endif
#endif
